---
- name: Get updated files from git repository
  git:
    repo: "{{project_repo}}"
    version:  "{{repo_branch}}"
    dest: "{{project_root_dir}}"
  when: git_pull_required

- name: Prepare clean
  tags: ['prepare', 'prepare:clean']
  file: path={{project_root_dir}}/dist state=absent

- name: Prepare install libraries
  tags: ['prepare', 'prepare:install:npm']
  command: npm install --silent
  args:
    chdir: "{{project_root_dir}}"

- name: Prepare install dev-libraries
  tags: ['prepare', 'prepare:install:npm']
  command: npm install --silent --only=dev
  args:
    chdir: "{{project_root_dir}}"

- name: Prepare install typings
  tags: ['prepare', 'prepare:install:typings']
  command: typings install
  args:
    chdir: "{{project_root_dir}}"
  when: typings_installer

- name: Compile test execution
  tags: ['compile', 'compile:test']
  command: smild test
  args:
    chdir: "{{project_root_dir}}"

- name: Compile minify build project
  tags: ['compile', 'compile:build']
  command: smild build {{smild_target_build}} -r
  args:
    chdir: "{{project_root_dir}}"
  when: minify_smild

- name: Compile build project
  tags: ['compile', 'compile:build']
  command: smild build {{smild_target_build}}
  args:
    chdir: "{{project_root_dir}}"
  when: not minify_smild

- name: Sync the s3 bucket
  tags: ['s3','s3:sync']
  command: aws s3 sync {{project_root_dir}}/dist/ s3://{{s3_bucket}} --delete
  when: s3_sync

- name: Docker clean context
  file: path={{docker_build_path}}/build/ state=absent
  tags: ['docker', 'docker:clean']
  when: docker_build

- name: Docker prepare context
  synchronize:
    src: "{{project_root_dir}}/dist/"
    dest: "{{docker_build_path}}/build/"
    delete: yes
    archive: no
    recursive: yes
  when: docker_build

- name: Docker build image
  tags: ['docker', 'docker:build']
  command: docker build --rm=true --tag {{docker_image_tag}} {{docker_build_path}}
  when: docker_build

- name: Docker push image
  tags: ['docker', 'docker:push']
  command: docker push {{docker_image_tag}}
  when: docker_push